# Generated by Django 4.2.16 on 2026-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead'), ('MANAGER', 'Manager')], max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('CONTRACT', 'Contract'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('skills_required', models.TextField(help_text='Enter skills separated by commas')),
                ('apply_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
