# Generated by Django 4.2.16 on 2026-06-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_job_description_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(default='https://www.linkedin.com/company/neurotech-circuits-private-limited/jobs/'),
        ),
    ]
